buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.0.197'
    }
}
        
apply plugin: 'net.minecraftforge.gradle'

version = '1.0.0'
group = 'xluke44.slotguard'
archivesBaseName = 'slotguard'

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859'
}


jar {
    manifest {
        attributes([
            "Specification-Title": "SlotGuard",
            "Specification-Vendor": "XLuke44",
            "Specification-Version": version,
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"XLuke44",
            "FMLCorePlugin": "xluke44.slotguard.SlotGuardCorePlugin",
            "FMLCorePluginContainsFMLMod": "true",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')
